name: axiomretailfashion
services:
  postgres:
    image: postgres:15
    container_name: axiomretailfashion_postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: retail_fashion
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -q -h postgres"
      interval: 10s
      timeout: 5s
      retries: 30

volumes:
  postgres_data: